version: '3.5'
services:
  app:
    container_name: notification_service
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    command: ["npm", "run", "dev"]

networks:
  default:
    external:
      name: schoolar-network

